### ISSUE TITLE
Requirement macOS 10.12?

### ISSUE THREAD

**Issue by schwantuschke** [josh-/TodayFlights#1]
I can not start the app because I get the info that OS X 10.12 is required. I have OS X 10.11.6.

**Comment by josh-** [comment]
@foomep Out of interest, why have you not updated to macOS 10.12?

I don't have access to a machine running 10.11 (not want to spend the time setting up a VM) but would be open to dropping down the required version if you or someone else was able to compile the application and test it on that OS?

**Comment by schwantuschke** [comment]
@josh- I use a old Version of Lightroom with have problems with Sierra. But I think I should update :)

**Comment by josh-** [comment]
Sounds good – hope you're able to update and use TodayFlights! Let me know if you encounter any issues or have any questions 😄

**Comment by hatemzidi** [comment]
hey, 

I just finished to compile the app on 10.11.6 .. so far everything is stable :)
