### ISSUE TITLE
Does not work on 10.11

### ISSUE THREAD

**Issue by iemg** [josh-/TodayFlights#3]
Does not work on 10.11, requests 10.12 as minimum requirement.

**Comment by bradyjoh** [comment]
+1 does not work on 10.14.4, when I try to open it it seems to crash.

**Comment by AlexanderVarela** [comment]
The app is not working, it crashes.

**Comment by josh-** [comment]
Hey all, sorry for the delay – I've [just realised v1.1](https://github.com/josh-/TodayFlights/releases/tag/v1.1) which incorporates #4 and should resolve this issue!
