### ISSUE TITLE
Crash on 10.15

### ISSUE THREAD

**Issue by ericmoret** [josh-/TodayFlights#5]

**Comment by cliffordp** [comment]
Same. A _hard_ crash.

**Comment by josh-** [comment]
Hey @ericmoret and @cliffordp, sorry for the delay – I've [just realised v1.1](https://github.com/josh-/TodayFlights/releases/tag/v1.1) which should hopefully resolve the issue, could you please let me know if it still isn't working? Thanks!

**Comment by cliffordp** [comment]
Confirmed latest is not crashing. Thanks!

Just don't know how to use it -- what's an Airline Code or Route Number? Maybe a link in the readme would be helpful.

**Comment by josh-** [comment]
Excellent, thanks @cliffordp!

For a flight code like `MH129`, the Airline Code is `MH` and the Route Number is `129` – that's a really good point though, I'll update the README and add some instructional text under the text boxes 👍

**Comment by josh-** [comment]
Something like this?

<img width="339" alt="image" src="https://user-images.githubusercontent.com/712727/91713648-832fea80-ebcd-11ea-83cf-3eb2b9854b61.png">
